# Generated by Django 3.2.5 on 2021-07-26 02:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Nombre del articulo', unique=True, verbose_name='Nombre del articulo')),
                ('desc', models.TextField(blank=True, help_text='Descripción', max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs/article/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('type_article', models.CharField(choices=[('FIJO', 'Fijo'), ('OPCIONAL', 'Opcional')], default='OPCIONAL', max_length=8)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nombre de Empresa', max_length=150, verbose_name='Nombre de Empresa')),
                ('Legal_representative', models.CharField(help_text='Name Legal representative', max_length=150, verbose_name='Name Legal representative')),
                ('nit', models.CharField(help_text='Nombre Completo', max_length=13, verbose_name='Nit')),
                ('company_address', models.TextField(blank=True, help_text='Dirección de la Empresa', null=True, verbose_name='Dirección de la Empresa')),
                ('phone', models.CharField(blank=True, help_text='Teléfono Empresa', max_length=20, null=True, verbose_name='Teléfono Empresa')),
                ('city', models.CharField(blank=True, help_text='Ciudad', max_length=150, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Companies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Nombre Completo', max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(help_text='Correo electrónico', max_length=255, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, help_text='Teléfono celular', max_length=20, null=True, verbose_name='Teléfono celular')),
                ('city', models.CharField(blank=True, help_text='Ciudad', max_length=150, null=True, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Costumer',
                'verbose_name_plural': 'Costumers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentaje de descuento', max_digits=3, verbose_name='Percentaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del plan', max_length=150, unique=True, verbose_name='Nombre del plan')),
                ('desc', models.TextField(blank=True, help_text='Descripción', max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs/plan/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Nombre del servicio', unique=True, verbose_name='Nombre del servicio')),
                ('desc', models.TextField(blank=True, help_text='Descripción', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs/service/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Impuestos', max_digits=3, verbose_name='Impuestos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('time', models.DateTimeField(verbose_name='Hora')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.article')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.costumer')),
                ('discounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.discount')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.service')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.tax')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aps.service'),
        ),
    ]
